version: "3.8"

services:
  mongo-rs-1:
    image: mongo:7.0.6
    ports:
      - "27017:27017"
    command: ["bash", "-c", "echo $MONGO_RS_KEYFILE_CONTENT > /data/keyfile && chmod 400 /data/keyfile && chown 999:999 /data/keyfile && docker-entrypoint.sh mongod --replSet rs0 --keyFile /data/keyfile --bind_ip_all"]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_RS_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_RS_ROOT_PASSWORD}
      - MONGO_RS_KEYFILE_CONTENT=${MONGO_RS_KEYFILE_CONTENT}
    volumes:
      - mongodb-rs-1-data:/data/db
    networks:
      - mongo-rs-net
    deploy:
      restart_policy:
        condition: on-failure

  mongo-rs-init:
    image: mongo:7.0.6
    command:
      - bash
      - -c
      - |
        echo "Waiting for mongo-rs-1 to be ready..."
        until mongosh --host mongo-rs-1 --eval "print(\"waited for connection\")"; do sleep 2; done
        echo "Initializing Replica Set..."
        mongosh --host mongo-rs-1 -u $$MONGO_INITDB_ROOT_USERNAME -p $$MONGO_INITDB_ROOT_PASSWORD --eval 'try { rs.status() } catch (err) { rs.initiate({_id: "rs0", members: [{_id: 0, host: "mongo-rs-1:27017"}]}) }'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_RS_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_RS_ROOT_PASSWORD}
    networks:
      - mongo-rs-net
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5

  mongo-rs-viewer:
    image: haohanyang/compass-web
    ports:
      - "5000:8080"
    links:
      - mongo-rs-1
    environment:
      - CW_MONGO_URI=${MONGO_RS_URI}
      - CW_BASIC_AUTH_USERNAME=${MONGO_VIEWER_USER}
      - CW_BASIC_AUTH_PASSWORD=${MONGO_VIEWER_PASS}
    networks:
      - mongo-rs-net
    deploy:
      restart_policy:
        condition: on-failure

  grafana:
    image: infra-grafana:local
    ports:
      - "5001:3000"
    links:
      - mongo-rs-1
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=haohanyang-mongodb-datasource
    networks:
      - mongo-rs-net
    deploy:
      restart_policy:
        condition: on-failure

networks:
  mongo-rs-net:
    driver: overlay
    attachable: true
    driver_opts:
      encrypted: "true"

volumes:
  mongodb-rs-1-data:
