version: "3.8"

services:
  mongo:
    image: mongo:7.0.11
    command: ["--noauth"]          # or remove this line if you want auth
    ports:
      - target: 27017                  # container port
        published: 27017               # host port (manager node)
        protocol: tcp
        mode: host                     # use "ingress" if you want VIP routing
    volumes:
      # host-binds must exist on every node that could run this task.
      # Using the manager only? A local bind is fine.
      - type: bind
        source: ./mongo-data           # make sure this path exists on host
        target: /data/db
    deploy:
      restart_policy:
        condition: any                 # closest Swarm equivalent to 'unless-stopped'
