version: "3.8"

services:
  dozzle:
    image: amir20/dozzle:latest
    environment:
      - DOZZLE_MODE=swarm
      - DOZZLE_AUTH_PROVIDER=simple
      - DOZZLE_ENABLE_ACTIONS=true
      - DOZZLE_ENABLE_SHELL=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - source: dozzle_users
        target: /data/users.yml
    networks:
      - reverse-proxy
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 60s

  cron:
    image: crazymax/swarm-cronjob:1.14.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=UTC
    deploy:
      mode: global

  prune-nodes:
    image: docker:27.3.1-cli
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: ["docker", "system", "prune", "--all", "--force"]
    deploy:
      mode: global
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=25 * * * *"
        - "swarm.cronjob.skip-running=false"
      restart_policy:
        condition: none

  mongodb:
    image: mongo:7.0.6
    ports:
      - "27017:27017"
    volumes:
      - /opt/mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    networks:
      - mongo
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 60s

  mongodb-rs:
    image: mongo:8.2.1
    ports:
      - "27018:27017"
    volumes:
      - mongodb-rs-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    command: >
      sh -c "
      cp /etc/mongodb-keyfile /tmp/mongodb-keyfile &&
      chmod 600 /tmp/mongodb-keyfile &&
      chown 999:999 /tmp/mongodb-keyfile &&
      exec mongod --replSet rs0 --bind_ip_all --keyFile /tmp/mongodb-keyfile
      "
    secrets:
      - source: mongodb-keyfile
        target: /etc/mongodb-keyfile
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    networks:
      - mongo
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 60s

  mongodb-rs-init:
    image: mongo:8.2.1
    environment:
      - MONGO_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    command: >
      sh -c "
      echo 'Waiting for MongoDB replica set to be ready...' &&
      sleep 20 &&
      echo 'Waiting for MongoDB to accept connections...' &&
      until mongosh --host mongodb-rs:27017 --eval 'db.adminCommand(\"ping\")' --quiet 2>/dev/null; do
        echo 'Waiting for MongoDB...';
        sleep 5;
      done &&
      echo 'Waiting for authentication to be ready...' &&
      sleep 10 &&
      until mongosh --host mongodb-rs:27017 -u $${MONGO_ROOT_USERNAME} -p $${MONGO_ROOT_PASSWORD} --authenticationDatabase admin --eval 'db.adminCommand(\"ping\")' --quiet 2>/dev/null; do
        echo 'Waiting for authentication...';
        sleep 5;
      done &&
      echo 'MongoDB is ready, checking replica set status...' &&
      mongosh --host mongodb-rs:27017 -u $${MONGO_ROOT_USERNAME} -p $${MONGO_ROOT_PASSWORD} --authenticationDatabase admin --quiet --eval '
        try {
          var status = rs.status();
          print(\"Replica set already initialized. Status: \" + status.set);
        } catch (e) {
          if (e.message.includes(\"no replset config has been received\")) {
            print(\"Initializing replica set...\");
            var result = rs.initiate({
              _id: \"rs0\",
              members: [{ _id: 0, host: \"mongodb-rs:27017\" }]
            });
            print(\"Replica set initialization initiated successfully\");
          } else {
            print(\"Error: \" + e.message);
            throw e;
          }
        }
      ' || exit 1 &&
      echo 'Replica set initialization completed'
      "
    networks:
      - mongo
    deploy:
      replicas: 1
      restart_policy:
        condition: none
      labels:
        - "swarm.cronjob.enable=false"

  mongo-viewer:
    image: haohanyang/compass-web
    depends_on:
      - mongodb
    environment:
      - CW_MONGO_URI=${MONGO_URI}
      - CW_BASIC_AUTH_USERNAME=${MONGO_VIEWER_USER}
      - CW_BASIC_AUTH_PASSWORD=${MONGO_VIEWER_PASS}
    networks:
      - mongo
      - reverse-proxy
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 60s

  mongo-backup-hourly:
    image: ghcr.io/vovastelmashchuk/mongo-backup:${GIT_COMMIT_SHA:-latest}
    command: ["/usr/local/bin/backup.sh"]
    depends_on:
      - cron
      - mongodb
    environment:
      - S3_ENDPOINT=${S3_ENDPOINT}
      - MONGO_URI=${MONGO_URI}
      - S3_BUCKET=backups
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_FOLDER=mongo-hourly
    networks:
      - mongo
    deploy:
      mode: replicated
      replicas: 0
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=0 * * * *"
        - "swarm.cronjob.skip-running=true"
      restart_policy:
        condition: none

  mongo-backup-daily:
    image: ghcr.io/vovastelmashchuk/mongo-backup:${GIT_COMMIT_SHA:-latest}
    command: ["/usr/local/bin/backup.sh"]
    depends_on:
      - cron
      - mongodb
    environment:
      - S3_ENDPOINT=${S3_ENDPOINT}
      - MONGO_URI=${MONGO_URI}
      - S3_BUCKET=backups
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_FOLDER=mongo-daily
    networks:
      - mongo
    deploy:
      mode: replicated
      replicas: 0
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=30 3 * * *"
        - "swarm.cronjob.skip-running=true"
      restart_policy:
        condition: none

  mongo-backup-weekly:
    image: ghcr.io/vovastelmashchuk/mongo-backup:${GIT_COMMIT_SHA:-latest}
    command: ["/usr/local/bin/backup.sh"]
    depends_on:
      - cron
      - mongodb
    environment:
      - S3_ENDPOINT=${S3_ENDPOINT}
      - MONGO_URI=${MONGO_URI}
      - S3_BUCKET=backups
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_FOLDER=mongo-weekly
    networks:
      - mongo
    deploy:
      mode: replicated
      replicas: 0
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=20 3 * * 2"
        - "swarm.cronjob.skip-running=true"
      restart_policy:
        condition: none

  caddy-backup-daily:
    image: ghcr.io/vovastelmashchuk/caddy-backup:${GIT_COMMIT_SHA:-latest}
    command: ["/usr/local/bin/backup.sh"]
    depends_on:
      - cron
      - caddy
    environment:
      - S3_ENDPOINT=${S3_ENDPOINT}
      - CADDY_DATA_DIR=/caddy_storage
      - S3_BUCKET=backups
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_FOLDER=caddy-daliy
    volumes:
      - /caddy_storage:/caddy_storage
    deploy:
      mode: replicated
      replicas: 0
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=0 5 * * *"
        - "swarm.cronjob.skip-running=true"
      restart_policy:
        condition: none

  caddy:
    image: ghcr.io/vovastelmashchuk/caddy:${GIT_COMMIT_SHA:-latest}
    dns:
      - 1.1.1.1
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /caddy_storage:/caddy_storage
    environment:
      - TZ=UTC
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: on-failure
    networks:
      - reverse-proxy

secrets:
  dozzle_users:
    external: true
  mongodb-keyfile:
    external: true

networks:
  reverse-proxy:
    driver: overlay
    attachable: true
  mongo:
    driver: overlay
    attachable: true

volumes:
  mongodb-rs-data:
