version: "3.8"

services:
  dozzle:
    image: amir20/dozzle:latest
    environment:
      - DOZZLE_MODE=swarm
      - DOZZLE_AUTH_PROVIDER=simple
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - source: dozzle_users
        target: /data/users.yml
    networks:
      - dozzle
      - reverse-proxy
    deploy:
      mode: global

  cron:
    image: crazymax/swarm-cronjob:1.14.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=UTC
    deploy:
      mode: global

  prune-nodes:
    image: docker:27.4.1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command:
      ["docker", "system", "prune", "--all", "--force", "--filter", "until=24h"]
    deploy:
      mode: global
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=0 2 * * *"
        - "swarm.cronjob.skip-running=false"
      restart_policy:
        condition: none

  mongodb-stage:
    image: mongo:7.0.6
    ports:
      - "27027:27017"
    volumes:
      - /opt/mongodb-data-stage:/data/db
    secrets:
      - mongo_root_username_stage
      - mongo_root_password_stage
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/mongo_root_username_stage
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo_root_password_stage
    networks:
      - mongo-stage
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 60s

  mongodb:
    image: mongo:7.0.6
    ports:
      - "2017:27017"
      - "27017:27017"
    volumes:
      - /opt/mongodb-data:/data/db
    secrets:
      - mongo_root_username
      - mongo_root_password
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/mongo_root_username
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo_root_password
    networks:
      - mongo
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 60s

  mongo-backup-hourly:
    image: ghcr.io/vovastelmashchuk/mongo-backup:${GIT_COMMIT_SHA:-latest}
    command: ["/usr/local/bin/backup.sh"]
    depends_on:
      - cron
      - mongodb
    environment:
      - S3_ENDPOINT=https://e4b7665fe955c028355a0e2f9e847b98.r2.cloudflarestorage.com
      - MONGO_URI=${MONGO_URI}
      - S3_BUCKET=backups
      - S3_ACCESS_KEY_ID=e77ffa5f293975926a41535bf32e1ca9
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_FOLDER=mongo-hourly
    networks:
      - mongo
    deploy:
      mode: replicated
      replicas: 0
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=0 * * * *"
        - "swarm.cronjob.skip-running=true"
      restart_policy:
        condition: none

  mongo-backup-daily:
    image: ghcr.io/vovastelmashchuk/mongo-backup:${GIT_COMMIT_SHA:-latest}
    command: ["/usr/local/bin/backup.sh"]
    depends_on:
      - cron
      - mongodb
    environment:
      - S3_ENDPOINT=https://e4b7665fe955c028355a0e2f9e847b98.r2.cloudflarestorage.com
      - MONGO_URI=${MONGO_URI}
      - S3_BUCKET=backups
      - S3_ACCESS_KEY_ID=e77ffa5f293975926a41535bf32e1ca9
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_FOLDER=mongo-daily
    networks:
      - mongo
    deploy:
      mode: replicated
      replicas: 0
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=30 3 * * *"
        - "swarm.cronjob.skip-running=true"
      restart_policy:
        condition: none

  mongo-backup-weekly:
    image: ghcr.io/vovastelmashchuk/mongo-backup:${GIT_COMMIT_SHA:-latest}
    command: ["/usr/local/bin/backup.sh"]
    depends_on:
      - cron
      - mongodb
    environment:
      - S3_ENDPOINT=https://e4b7665fe955c028355a0e2f9e847b98.r2.cloudflarestorage.com
      - MONGO_URI=${MONGO_URI}
      - S3_BUCKET=backups
      - S3_ACCESS_KEY_ID=e77ffa5f293975926a41535bf32e1ca9
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_FOLDER=mongo-weekly
    networks:
      - mongo
    deploy:
      mode: replicated
      replicas: 0
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=20 3 * * 2"
        - "swarm.cronjob.skip-running=true"
      restart_policy:
        condition: none

  caddy-backup-daily:
    image: ghcr.io/vovastelmashchuk/caddy-backup:${GIT_COMMIT_SHA:-latest}
    command: ["/usr/local/bin/backup.sh"]
    depends_on:
      - cron
      - caddy
    environment:
      - S3_ENDPOINT=https://e4b7665fe955c028355a0e2f9e847b98.r2.cloudflarestorage.com
      - S3_BUCKET=backups
      - S3_ACCESS_KEY_ID=e77ffa5f293975926a41535bf32e1ca9
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_FOLDER=caddy-daily
      - CADDY_DATA_DIR=/caddy_storage
    volumes:
      - /caddy_storage:/caddy_storage
    deploy:
      mode: replicated
      replicas: 0
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=6 * * * *"
        - "swarm.cronjob.skip-running=true"
      restart_policy:
        condition: none

  caddy:
    image: ghcr.io/vovastelmashchuk/caddy:${GIT_COMMIT_SHA:-latest}
    dns:
      - 1.1.1.1
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /caddy_storage:/caddy_storage
    environment:
      - TZ=UTC
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: on-failure
    networks:
      - reverse-proxy

secrets:
  mongo_root_username:
    external: true
  mongo_root_password:
    external: true
  mongo_root_username_stage:
    external: true
  mongo_root_password_stage:
    external: true
  dozzle_users:
    external: true

networks:
  reverse-proxy:
    driver: overlay
    attachable: true
  mongo:
    driver: overlay
    attachable: true
  mongo-stage:
    driver: overlay
    attachable: true
  dozzle:
    driver: overlay
