version: "3.8"

services:
  dozzle:
    image: amir20/dozzle:latest
    environment:
      - DOZZLE_MODE=swarm
      - DOZZLE_AUTH_PROVIDER=simple
      - DOZZLE_ENABLE_ACTIONS=true
      - DOZZLE_ENABLE_SHELL=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - source: dozzle_users
        target: /data/users.yml
    networks:
      - reverse-proxy
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 60s

  cron:
    image: crazymax/swarm-cronjob:1.14.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=UTC
    deploy:
      mode: global

  prune-nodes:
    image: docker:27.3.1-cli
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: ["docker", "system", "prune", "--all", "--force"]
    deploy:
      mode: global
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=25 * * * *"
        - "swarm.cronjob.skip-running=false"
      restart_policy:
        condition: none

  mongo-rs-1:
    image: mongo:8.2.3
    command: ["bash", "-c", "echo $MONGO_RS_KEYFILE_CONTENT > /data/keyfile && chmod 400 /data/keyfile && chown 999:999 /data/keyfile && docker-entrypoint.sh mongod --replSet rs0 --keyFile /data/keyfile --bind_ip_all"]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${PASSWORD}
      - MONGO_RS_KEYFILE_CONTENT=${MONGO_RS_KEYFILE_CONTENT}
    volumes:
      - mongodb-rs-1-data:/data/db
    networks:
      - mongo-rs-net
    deploy:
      restart_policy:
        condition: on-failure

  mongo-rs-init:
    image: mongo:8.2.3
    command:
      - bash
      - -c
      - |
        echo "Waiting for mongo-rs-1 to be ready..."
        until mongosh --host mongo-rs-1 --eval "print(\"waited for connection\")"; do sleep 2; done
        echo "Initializing Replica Set..."
        mongosh --host mongo-rs-1 -u $$MONGO_INITDB_ROOT_USERNAME -p $$MONGO_INITDB_ROOT_PASSWORD --eval 'try { rs.status() } catch (err) { rs.initiate({_id: "rs0", members: [{_id: 0, host: "mongo-rs-1:27017"}]}) }'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${PASSWORD}
    networks:
      - mongo-rs-net
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5

  mongo-rs-viewer:
    image: haohanyang/compass-web:0.3.1
    environment:
      - CW_MONGO_URI=mongodb://${MONGO_RS_ROOT_USERNAME}:${PASSWORD}@mongo-rs-1:27017/?replicaSet=rs0&authSource=admin
      - CW_BASIC_AUTH_USERNAME=${USERNAME}
      - CW_BASIC_AUTH_PASSWORD=${PASSWORD}
    networks:
      - mongo-rs-net
      - reverse-proxy
    deploy:
      restart_policy:
        condition: on-failure

  mongo-nu31-viewer:
    image: haohanyang/compass-web:0.3.1
    environment:
      - CW_MONGO_URI=${MONGO_NU_31_URI}
      - CW_BASIC_AUTH_USERNAME=${MONGO_NU31_VIEWER_USER}
      - CW_BASIC_AUTH_PASSWORD=${MONGO_NU31_VIEWER_PASS}
    networks:
      - mongo-rs-net
      - reverse-proxy
    deploy:
      restart_policy:
        condition: on-failure
  
  mongo-rs-backup-hourly:
    image: ghcr.io/vovastelmashchuk/mongo-rs-backup:${GIT_COMMIT_SHA:-latest}
    command: ["/usr/local/bin/backup.sh"]
    depends_on:
      - cron
      - mongo-rs-1
    environment:
      - S3_ENDPOINT=${S3_ENDPOINT}
      - MONGO_URI=${MONGO_RS_URI}
      - S3_BUCKET=backups
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_FOLDER=mongo-rs-hourly
    networks:
      - mongo-rs-net
    deploy:
      mode: replicated
      replicas: 0
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=0 * * * *"
        - "swarm.cronjob.skip-running=true"
      restart_policy:
        condition: none

  mongo-rs-backup-daily:
    image: ghcr.io/vovastelmashchuk/mongo-rs-backup:${GIT_COMMIT_SHA:-latest}
    command: ["/usr/local/bin/backup.sh"]
    depends_on:
      - cron
      - mongo-rs-1
    environment:
      - S3_ENDPOINT=${S3_ENDPOINT}
      - MONGO_URI=${MONGO_RS_URI}
      - S3_BUCKET=backups
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_FOLDER=mongo-rs-daily
    networks:
      - mongo-rs-net
    deploy:
      mode: replicated
      replicas: 0
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=30 3 * * *"
        - "swarm.cronjob.skip-running=true"
      restart_policy:
        condition: none

  mongo-rs-backup-weekly:
    image: ghcr.io/vovastelmashchuk/mongo-rs-backup:${GIT_COMMIT_SHA:-latest}
    command: ["/usr/local/bin/backup.sh"]
    depends_on:
      - cron
      - mongo-rs-1
    environment:
      - S3_ENDPOINT=${S3_ENDPOINT}
      - MONGO_URI=${MONGO_RS_URI}
      - S3_BUCKET=backups
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_FOLDER=mongo-rs-weekly
    networks:
      - mongo-rs-net
    deploy:
      mode: replicated
      replicas: 0
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=20 3 * * 2"
        - "swarm.cronjob.skip-running=true"
      restart_policy:
        condition: none

  caddy-backup-daily:
    image: ghcr.io/vovastelmashchuk/caddy-backup:${GIT_COMMIT_SHA:-latest}
    command: ["/usr/local/bin/backup.sh"]
    depends_on:
      - cron
      - caddy
    environment:
      - S3_ENDPOINT=${S3_ENDPOINT}
      - CADDY_DATA_DIR=/caddy_storage
      - S3_BUCKET=backups
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_FOLDER=caddy-daliy
    volumes:
      - /caddy_storage:/caddy_storage
    deploy:
      mode: replicated
      replicas: 0
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=0 5 * * *"
        - "swarm.cronjob.skip-running=true"
      restart_policy:
        condition: none

  caddy:
    image: ghcr.io/vovastelmashchuk/caddy:${GIT_COMMIT_SHA:-latest}
    dns:
      - 1.1.1.1
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"
    volumes:
      - /caddy_storage:/caddy_storage
    environment:
      - TZ=UTC
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: on-failure
    networks:
      - reverse-proxy

  grafana:
    image: ghcr.io/vovastelmashchuk/grafana:${GIT_COMMIT_SHA:-latest}
    links:
      - mongo-rs-1
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - TZ=UTC
      - GF_SECURITY_ADMIN_USER=${USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${PASSWORD}
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: on-failure
    networks:
      - reverse-proxy
      - mongo-rs-net

  grafana-backup-daily:
    image: ghcr.io/vovastelmashchuk/grafana-backup:${GIT_COMMIT_SHA:-latest}
    command: ["/usr/local/bin/backup.sh"]
    depends_on:
      - cron
      - grafana
    environment:
      - S3_ENDPOINT=${S3_ENDPOINT}
      - GRAFANA_DATA_DIR=/var/lib/grafana/grafana.db
      - S3_BUCKET=backups
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_FOLDER=grafana-daily
    volumes:
      - grafana-data:/var/lib/grafana
    deploy:
      mode: replicated
      replicas: 0
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=0 6 * * *"
        - "swarm.cronjob.skip-running=true"
      restart_policy:
        condition: none

  telegraf:
    image: ghcr.io/vovastelmashchuk/telegraf:${GIT_COMMIT_SHA:-latest}
    hostname: "{{.Node.Hostname}}"
    networks:
      - mongo-rs-net
    environment:
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
      - HOST_ETC=/host/etc
      - MONGO_URL=mongodb://${MONGO_RS_ROOT_USERNAME}:${PASSWORD}@mongo-rs-1:27017/?replicaSet=rs0&authSource=admin
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/host/proc
      - /sys:/host/sys
      - /etc:/host/etc
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

secrets:
  dozzle_users:
    external: true

networks:
  reverse-proxy:
    driver: overlay
    attachable: true
  mongo-rs-net:
    driver: overlay
    attachable: true
    driver_opts:
      encrypted: "true"

volumes:
  mongodb-rs-1-data:
  grafana-data:
