version: "3.8"

services:
  dozzle:
    image: amir20/dozzle:latest
    environment:
      - DOZZLE_MODE=swarm
      - DOZZLE_AUTH_PROVIDER=simple
      - DOZZLE_ENABLE_ACTIONS=true
      - DOZZLE_ENABLE_SHELL=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - source: dozzle_users
        target: /data/users.yml
    networks:
      - reverse-proxy
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 60s

  cron:
    image: crazymax/swarm-cronjob:1.14.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=UTC
    deploy:
      mode: global

  prune-nodes:
    image: docker:27.3.1-cli
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: ["docker", "system", "prune", "--all", "--force"]
    deploy:
      mode: global
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=25 * * * *"
        - "swarm.cronjob.skip-running=false"
      restart_policy:
        condition: none

  mongodb:
    image: mongo:7.0.6
    ports:
      - "2017:27017"
      - "27017:27017"
    volumes:
      - /opt/mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    networks:
      - mongo
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 60s

  mongo-viewer:
    image: haohanyang/compass-web
    depends_on:
      - mongodb
    environment:
      - CW_MONGO_URI=${MONGO_URI}
      - CW_BASIC_AUTH_USERNAME=${MONGO_VIEWER_USER}
      - CW_BASIC_AUTH_PASSWORD=${MONGO_VIEWER_PASS}
    networks:
      - mongo
      - reverse-proxy
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 60s

  mongo-backup-hourly:
    image: ghcr.io/vovastelmashchuk/mongo-backup:${GIT_COMMIT_SHA:-latest}
    command: ["/usr/local/bin/backup.sh"]
    depends_on:
      - cron
      - mongodb
    environment:
      - S3_ENDPOINT=${S3_ENDPOINT}
      - MONGO_URI=${MONGO_URI}
      - S3_BUCKET=backups
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_FOLDER=mongo-hourly
    networks:
      - mongo
    deploy:
      mode: replicated
      replicas: 0
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=0 * * * *"
        - "swarm.cronjob.skip-running=true"
      restart_policy:
        condition: none

  mongo-backup-daily:
    image: ghcr.io/vovastelmashchuk/mongo-backup:${GIT_COMMIT_SHA:-latest}
    command: ["/usr/local/bin/backup.sh"]
    depends_on:
      - cron
      - mongodb
    environment:
      - S3_ENDPOINT=${S3_ENDPOINT}
      - MONGO_URI=${MONGO_URI}
      - S3_BUCKET=backups
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_FOLDER=mongo-daily
    networks:
      - mongo
    deploy:
      mode: replicated
      replicas: 0
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=30 3 * * *"
        - "swarm.cronjob.skip-running=true"
      restart_policy:
        condition: none

  mongo-backup-weekly:
    image: ghcr.io/vovastelmashchuk/mongo-backup:${GIT_COMMIT_SHA:-latest}
    command: ["/usr/local/bin/backup.sh"]
    depends_on:
      - cron
      - mongodb
    environment:
      - S3_ENDPOINT=${S3_ENDPOINT}
      - MONGO_URI=${MONGO_URI}
      - S3_BUCKET=backups
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_FOLDER=mongo-weekly
    networks:
      - mongo
    deploy:
      mode: replicated
      replicas: 0
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=20 3 * * 2"
        - "swarm.cronjob.skip-running=true"
      restart_policy:
        condition: none

  caddy-backup-daily:
    image: ghcr.io/vovastelmashchuk/caddy-backup:${GIT_COMMIT_SHA:-latest}
    command: ["/usr/local/bin/backup.sh"]
    depends_on:
      - cron
      - caddy
    environment:
      - S3_ENDPOINT=${S3_ENDPOINT}
      - CADDY_DATA_DIR=/caddy_storage
      - S3_BUCKET=backups
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_FOLDER=caddy-daliy
    volumes:
      - /caddy_storage:/caddy_storage
    deploy:
      mode: replicated
      replicas: 0
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=0 5 * * *"
        - "swarm.cronjob.skip-running=true"
      restart_policy:
        condition: none

  caddy:
    image: ghcr.io/vovastelmashchuk/caddy:${GIT_COMMIT_SHA:-latest}
    dns:
      - 1.1.1.1
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /caddy_storage:/caddy_storage
    environment:
      - TZ=UTC
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: on-failure
    networks:
      - reverse-proxy

secrets:
  dozzle_users:
    external: true

networks:
  reverse-proxy:
    driver: overlay
    attachable: true
  mongo:
    driver: overlay
    attachable: true
