version: "3.8"

services:
  mongodb:
    image: mongo:7.0.6
    network_mode: "host"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_ROOT_USERNAME=root
