version: "3.8"

services:
  mongodb:
    image: mongo:7.0.6
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - mongo
    deploy:
      mode: global

  mongo-viewer:
    image: haohanyang/compass-web
    ports:
      - "5000:8080"
    environment:
      - CW_MONGO_URI=mongodb://mongodb:27017
    networks:
      - mongo
    deploy:
      mode: replicated
      replicas: 1

networks:
  mongo:
    driver: overlay
    attachable: true

volumes:
  mongodb-data:
