{
 "title": "VPS Metrics",
 "description": "VPS Metrics collected by Alloy and stored in Prometheus.",
 "tags": [
  "infra",
  "vps"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "CPU Usage (Active %)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=~\"(/|/rootfs)\"} - node_filesystem_avail_bytes{mountpoint=~\"(/|/rootfs)\"}",
     "legendFormat": "Used (Bytes)"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=~\"(/|/rootfs)\"}",
     "legendFormat": "Total Capacity"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=~\"(/|/rootfs)\"} * 0.8",
     "legendFormat": "80% Threshold"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=~\"(/|/rootfs)\"} * 100) / node_filesystem_size_bytes{mountpoint=~\"(/|/rootfs)\"})",
     "legendFormat": "Used (%)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "Used (Bytes)"
    },
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "Total Capacity" },
    {
     "expr": "node_memory_MemTotal_bytes * 0.8",
     "legendFormat": "80% Threshold"
    },
    {
     "expr": "100 * (1 - ((node_memory_MemAvailable_bytes) / (node_memory_MemTotal_bytes)))",
     "legendFormat": "Used (%)"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device!~\"lo|docker.+|veth.+\"}[1m])",
     "legendFormat": "Receive - {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device!~\"lo|docker.+|veth.+\"}[1m])",
     "legendFormat": "Transmit - {{device}}"
    }
   ]
  },
  {
   "title": "Stacks",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (container_label_com_docker_stack_namespace) (container_last_seen{container_label_com_docker_stack_namespace!=\"\"})",
     "legendFormat": "{{container_label_com_docker_stack_namespace}}"
    }
   ]
  },
  {
   "title": "Services Replica Count",
   "type": "stat",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (container_label_com_docker_stack_namespace, container_label_com_docker_swarm_service_name) (container_last_seen{container_label_com_docker_swarm_service_name!=\"\"})",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    }
   ]
  }
 ]
}